CREATE TABLE IF NOT EXISTS `jos_member` (
  `id` int(12) NOT NULL auto_increment,
  `number` int(12) default NULL,
  `name` varchar(50) NOT NULL default '',
  `position` varchar(100) default NULL,
  `residence` varchar(100) default NULL,
  `nicknames` varchar(200) default NULL,
  `dob` date default NULL,
  `nationality` varchar(50) default NULL,
  `clubhistory` mediumtext,
  `honours` mediumtext,
  `about` mediumtext,
  `quote` varchar(200) default NULL,
  `hometown` varchar(200) default NULL,
  `fave_player` varchar(200) default NULL,
  `height_weight` varchar(200) default NULL,
  `school_attending` varchar(200) default NULL,
  `graduating_class` varchar(200) default NULL,
  `gpa` varchar(200) default NULL,
  `sat_act` varchar(200) default NULL,
  `level_rating` varchar(200) default NULL,
  `decision_makers` text(500) default NULL,
  `travel_schedule` text(500) default NULL,
  `hobbies` text(500) default NULL,
  `conference` text(500) default NULL,
  `picture` varchar(200) default NULL,
  `leaving_date` date default NULL,
  `joining_date` date default NULL,
  `first_name` varchar(20) NOT NULL default '',
  `middle_name` varchar(20) default NULL,
  `surname` varchar(20) NOT NULL default '',
  `published` tinyint(1) unsigned NOT NULL default '0',
  `checked_out` int(11) unsigned NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `ordering` int(11) NOT NULL default '0',
  `params` text NOT NULL,
  `user_id` int(11) NOT NULL default '0',
  `catid` int(11) NOT NULL default '0',
  `access` tinyint(3) unsigned NOT NULL default '0',
  `alias` varchar(255) NOT NULL default '',
  `email_to` varchar(60) default '',
  `description` text(500) default '',
  PRIMARY KEY  (`id`)
);

CREATE TABLE IF NOT EXISTS `jos_clubcategories` (
  `id` int(12) NOT NULL auto_increment,
  `name` varchar(50) NOT NULL default '',
  `alias` varchar(255) NOT NULL default '',
  `published` tinyint(1) unsigned NOT NULL default '0',
  `checked_out` int(11) unsigned NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `editor` varchar(150) NOT NULL default '',
  `ordering` int(11) NOT NULL default '0',
  `params` text NOT NULL,
  `access` tinyint(3) unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`)
);
